# Generated by Django 6.0.1 on 2026-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Optional phone number', max_length=20)),
                ('goal', models.CharField(help_text="What the user wants to achieve (e.g., 'Lose weight', 'Build muscle')", max_length=200)),
                ('message', models.TextField(help_text='Additional message or details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False, help_text='Has this lead been contacted?')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this lead')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
