# Generated by Django 6.0.1 on 2026-01-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('short_description', models.TextField(help_text='Brief description for card display (recommended: 100-150 characters)')),
                ('full_description', models.TextField(help_text='Full description for detail view')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Optional price (leave blank for 'Contact for pricing')", max_digits=10, null=True)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated tags (e.g., 'weight-loss, beginner, meal-prep')", max_length=500)),
                ('image', models.ImageField(help_text='Plan image (will be resized to max 800px width)', upload_to='plans/')),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are shown on the public site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan/Program',
                'verbose_name_plural': 'Plans/Programs',
                'ordering': ['-created_at'],
            },
        ),
    ]
